source 'git@github.com:wanyakun/Specs.git'
source 'git@github.com:CocoaPods/Specs.git'

platform :ios, "10.0"
use_frameworks!

target 'YKNetworking_Example' do
  pod 'YKNetworking', :path => '../'

  target 'YKNetworking_Tests' do
    inherit! :search_paths

    
  end
end
